### ISSUE TITLE
Wrong warning message or wrong resolution

### ISSUE THREAD

**Issue by sgandon** [iloveeclipse/plugindependencies#1]
Hello
I think this set of plugin are a great initiatives.
It lacks of documentation and I am not usre how to use it especially the _resolution_ view.
Anyway I have spoted something that looks like a bug.
I have a warning that one of the package exported by the bundle is exported by another bundle.
But when I look deeper I only get one bundle exporting it.
see image below.

<img width="895" alt="java_-_components-salesforce_src_test_java_org_talend_components_salesforce_salesforcelocalcomponenttestit_java_-_eclipse_-__users_sgandon_talend_java_eclipse_workspaces_components" src="https://cloud.githubusercontent.com/assets/783286/11539652/84f9b9ce-9928-11e5-91a1-3c63f8698115.png">

**Comment by iloveeclipse** [comment]
Yep, looks like a bug. Since I haven't added tracing functionality yet, I can't say why it happens. My guess is that some of the plugins were left unresolved (such plugins aren't shown yet too) but they could contribute that second package. BTW if you like you could debug it - the source code is open.
